version: "3.7"
services:
  nginx:
    restart: always
    image: nginx:latest
    container_name: gces_tpi_nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    links:
      - frontend
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
  frontend:
    build: library_front
    container_name: gces_tpi_front
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - backend
  backend:
    build: library_back
    container_name: gces_tpi_back
    ports:
      - 8000:8000
    env_file:
      - ./library_back/.env
    depends_on:
      - postgres
  postgres:
    build: postgres
    container_name: gces_tpi_db
    ports:
      - 5432:5432
    volumes:
      - library-vol:/var/lib/postgresql/data
volumes:
  library-vol: