name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: "build"
    steps:
    - name: Checkout v3
      uses: actions/checkout@v3
    - name: Build docker
      run: docker-compose build --no-cache

