name: Deploy

on:
  workflow_run:
    workflows: ["Test CI"]
    branches: [main]
    types: 
      - completed

jobs:
  backend-deploy:
    name: "build and deploy backend"
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: actions/checkout@v3
    - name: login to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: build and deploy docker image
      uses: docker/build-push-action@v4
      with:
        context: ./library_back
        file: ./library_back/Dockerfile
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/library_back:latest
        push: true
  frontend-deploy:
    name: "build and deploy frontend"
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: actions/checkout@v3
    - name: login to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: build and deploy docker image
      uses: docker/build-push-action@v4
      with:
        context: ./library_front
        file: ./library_front/Dockerfile
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/library_front:latest
        push: true
