name: Lint CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-lint:
    name: "backend lint"
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    defaults:
      run:
        working-directory: ./library_back
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: set up python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: install flake 8
        run: |
          python -m pip install --upgrade pip
          pip3 install flake8
      - name: run flake 8
        run: flake8 --count --select=F6,F7,F8,E9 --exclude=*.pyc,*migrations* --statistics
          
  frontend-lint:
    runs-on: ubuntu-latest
    name: "frontend lint"
    defaults:
       run:
         working-directory: ./library_front
    strategy:
      max-parallel: 4
      matrix:
        node-version: [18.12.x]
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: run npm install
        run: |
          npm install
      - name: exec eslint
        run: npm exec eslint ./src
