name: Test CI

on:
  workflow_run:
    workflows: ["Build CI"]
    types: 
      - completed
      
jobs:
  tests:  
    runs-on: ubuntu-latest
    name: "test"
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: library_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
    steps:
    - name: Checkout v3
      uses: actions/checkout@v3
    - name: test backend
      run: docker-compose run backend python manage.py test
    - name: test frontent
      run: docker-compose run frontend npm run test
      
